/*******************************************************************************************************************
 * Authors:   SanAndreasP
 * Copyright: SanAndreasP
 * License:   Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
 *                http://creativecommons.org/licenses/by-nc-sa/4.0/
 *******************************************************************************************************************/
package de.sanandrew.mods.particledeco.util;

import cpw.mods.fml.client.event.ConfigChangedEvent.OnConfigChangedEvent;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.eventhandler.EventBus;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;
import cpw.mods.fml.common.network.FMLEventChannel;
import cpw.mods.fml.common.network.NetworkRegistry;

@Mod(modid = PDM_Main.MOD_ID, version = PDM_Main.VERSION, name = "Turret Mod", //guiFactory = TM_Main.MOD_GUI_FACTORY,
     dependencies = "required-after:sapmanpack@[2.0.0,)")
public final class PDM_Main
{
    public static final String MOD_ID = "particledeco";
    public static final String VERSION = "2.0.0";
    public static final String MOD_LOG = "ParticleDeco";
    public static final String MOD_CHANNEL = "ParticleDecoNWCH";
//    public static final String MOD_GUI_FACTORY = "de.sanandrew.mods.claysoldiers.client.gui.ModGuiFactory";

    private static final String MOD_PROXY_CLIENT = "de.sanandrew.mods.particledeco.client.util.ClientProxy";
    private static final String MOD_PROXY_COMMON = "de.sanandrew.mods.particledeco.util.CommonProxy";

    @Mod.Instance(PDM_Main.MOD_ID)
    public static PDM_Main instance;
    @SidedProxy(modId = PDM_Main.MOD_ID, clientSide = PDM_Main.MOD_PROXY_CLIENT, serverSide = PDM_Main.MOD_PROXY_COMMON)
    public static CommonProxy proxy;
    public static FMLEventChannel channel;

    public static final EventBus EVENT_BUS = new EventBus();

//    public static CreativeTabs clayTab = new CreativeTabClaySoldiers();


    @Mod.EventHandler
    public void modPreInit(FMLPreInitializationEvent event) {
        event.getModMetadata().autogenerated = false;

//        ModConfig.config = new Configuration(event.getSuggestedConfigurationFile());
//        ModConfig.syncConfig();
//
        RegistryItems.initialize();
        RegistryBlocks.initialize();

        NetworkRegistry.INSTANCE.registerGuiHandler(this, new GuiHandler());
    }

    @Mod.EventHandler
    public void modInit(FMLInitializationEvent event) {
//        RegistryRecipes.initialize();

        FMLCommonHandler.instance().bus().register(this);

        channel = NetworkRegistry.INSTANCE.newEventDrivenChannel(MOD_CHANNEL);

        proxy.modInit();

        RegistryEntities.registerEntities(this);
    }

    @SubscribeEvent
    public void onConfigChanged(OnConfigChangedEvent eventArgs) {
        if( eventArgs.modID.equals(MOD_ID) ) {
//            ModConfig.syncConfig();
        }
    }
}
